# Generated by Django 5.1.7 on 2025-03-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0004_alter_personnel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jour', models.DateField(auto_now_add=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Présent', 'Présent'), ('Absent', 'Absent'), ('Retard', 'Retard'), ('Congé', 'Congé')], default='Présent', max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
        ),
    ]
