# Generated by Django 5.1.7 on 2025-03-21 12:32

import django.db.models.deletion
import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0004_alter_personnel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to=document.models.document_upload_path)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personnel.personnel')),
            ],
        ),
    ]
