# Generated by Django 4.2.3 on 2023-07-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tache.etat')),
                ('personnel', models.ManyToManyField(to='personnel.personnel')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.utilisateur')),
            ],
        ),
    ]
