# Generated by Django 4.2.3 on 2023-07-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('personnel', '0001_initial'),
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taches',
            new_name='Tache',
        ),
    ]
