# Generated by Django 4.2.3 on 2023-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0002_rename_taches_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='etat',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A Faire'), (2, 'En Cours'), (3, 'En Test'), (4, 'Terminé')], default=1),
        ),
        migrations.DeleteModel(
            name='Etat',
        ),
    ]
