# Generated by Django 4.2.3 on 2023-07-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0003_alter_tache_etat_delete_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='personnel',
        ),
    ]
