# Generated by Django 4.2.3 on 2023-08-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_remove_personnel_responsable_service_responsable'),
        ('tache', '0004_remove_tache_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='tache',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.service'),
        ),
    ]
