# Generated by Django 4.2.3 on 2023-08-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0005_tache_personnel_tache_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
