# Generated by Django 4.2.3 on 2023-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0006_alter_tache_date_debut_alter_tache_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
