# Generated by Django 5.1.7 on 2025-03-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0004_alter_personnel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Espèces', 'Espèces')], max_length=50)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Effectué', 'Effectué')], default='En attente', max_length=20)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
                ('salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiement.salaire')),
            ],
        ),
    ]
