# Generated by Django 4.2.3 on 2023-07-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=14)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
    ]
