# Generated by Django 4.2.3 on 2023-07-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_alter_utilisateur_nom_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nom_utilisateur',
            new_name='username',
        ),
    ]
