# Generated by Django 5.1.7 on 2025-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_zoomtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomtoken',
            name='expires_in',
            field=models.CharField(max_length=50),
        ),
    ]
