# Generated by Django 4.2.3 on 2023-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
