# Generated by Django 4.2.3 on 2023-07-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_date_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='responsable',
        ),
        migrations.AddField(
            model_name='service',
            name='responsable',
            field=models.ManyToManyField(related_name='responsable', to='personnel.personnel'),
        ),
    ]
